name: TMDbBuild

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Set Secret Properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" > ./local.properties

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'tmdb_keystore.jks'
          fileDir: './app/keystore/'
          encodedString: ${{ secrets.TMDB_KEYSTORE }}

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build Release
        run: ./gradlew assembleRelease

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: TMDb Release ${{ github.ref }}
          artifacts: "app/build/outputs/apk/release/TMDb.apk"

      - name: Upload Build Artifact
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
          testers: ${{ secrets.FIREBASE_TESTERS }}
          file: app/build/outputs/apk/release/TMDb.apk